config/routes.rb
GoogleMapsTut::Application.routes.draw do
      
  root "pages#home"
  
  get "/home", to: "pages#home", as: "home"
  get "/geocoding", to: "pages#geocoding", as: "geocoding"
  get "/reverse_geocoding", to: "pages#reverse_geocoding", as: "reverse_geocoding"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end
  
  def geocoding
    respond_to do |format|               
      format.js
    end
  end
  
  def reverse_geocoding
    respond_to do |format|               
      format.js
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | GoogleMapsTut"      
    end
  end
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    
    <div class="row footer-first-row">
      
      <div class="col-xs-12 text-center">
        <p><small>
          &copy; 2014 - SitePoint: Integrate Google Maps Tutorial
          <br/>
          Boilerplate with: <%= link_to "RailsBricks", "http://www.railsbricks.net" %>
        </small></p>
      </div>
      
    </div>
    
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "GoogleMapsTut" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
    <!--[if lt IE 9]>
    <%= javascript_include_tag "respond" %>
    <%= javascript_include_tag "html5shiv" %>
  <![endif]-->
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      
    <div class="container">
       
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>     
      </div>  
      
    </div>
  </div>
    
  <%= render 'layouts/footer' %>    

</body>
</html>

app/views/pages/geocoding.js.erb
$('#reverse_geocoding_fields').hide();
$('#geocoding_fields').show();
$('#geocoding').addClass('active');
$('#reverse_geocoding').removeClass('active');

app/views/pages/home.html.erb
<% title("Home Page") %>
<h1>Google Maps Tut</h1>
<div id="search_options">
  <%= link_to "Geocding search", geocoding_path, remote: true, id: "geocoding"%>
  <%= link_to "Reverse geocding search", reverse_geocoding_path, remote: true, id: "reverse_geocoding"%>
</div>
<div id="map-container">
	<div id="map-canvas"></div>
 
  <div id="geocoding_fields">
    <%= text_field_tag :search, params[:search], placeholder: "Enter a place", :id => 'search_box_geocoding', class: 'search_box' %>
    <%= button_tag "Search", id: "submit_button_geocoding", data: { disable_with: "Please wait..." }, class: "submit_button" %> 
  </div>
  <div id="reverse_geocoding_fields">
    <%= text_field_tag :search, params[:search], placeholder: "Enter a point (latitude, longitude)", :id => 'search_box_reverse', class: 'search_box' %>
    <%= button_tag "Search", id: "submit_button_reverse", data: { disable_with: "Please wait..." }, class: "submit_button" %> 
  </div>
</div>

app/views/pages/reverse_geocoding.js.erb
$('#geocoding_fields').hide();
$('#reverse_geocoding_fields').show();
$('#reverse_geocoding').addClass('active');
$('#geocoding').removeClass('active');